<?php
define('ACCOUNT_SCOMM_ACTION_CREATE_ACCOUNT',128);

define('SERVER_RESPONSE_HEADER','WiChatSR');
define('SERVER_RESPONSE_HEADER_LEN','8');

define('RESPONSE_NONE',0);
define('RESPONSE_SUCCESS',1);
define('RESPONSE_BUSY',2);
define('RESPONSE_INVALID',3);
define('RESPONSE_DEVICE_UNSUPPORTED',4);
define('RESPONSE_FAILED',5);
define('RESPONSE_NEED_LOGIN',6);
define('RESPONSE_DATE_EXPIRED',7);
define('RESPONSE_IN_MAINTANANCE',8);

define('RESPONSE_ACCOUNT_NONE',0);
define('RESPONSE_ACCOUNT_PASSWORD_OK',1);
define('RESPONSE_ACCOUNT_ID_EXISTS',2);
define('RESPONSE_ACCOUNT_ACCOUNT_OK',3);

define('ACCOUNT_WEB_ROOT','127.0.0.1/Account');

define('ACCOUNT_SCOMM_WEB_KEY','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'); 
?>